# https://github.com/samuelmeuli/action-electron-builder
name: Build Executables

on:
  pull_request:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: setup dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev  libudev-dev

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps with big timeout
        run: |
          yarn install --network-timeout 600000

      - name: Build App Binaries
        run: |
          yarn electron:build


